// App constants
export const appActions = {
  INITIALIZE_APP: 'APP/INITIALIZE_APP',
  SET_INITIALIZE_APP: 'APP/SET_INITIALIZE_APP'
};

export const postActions = {
  SET_LOADER: 'SET_LOADER',
  GET_POST_REQUEST: 'GET_POST_REQUEST',
  SET_POST_REQUEST: 'SET_POST_REQUEST'
};
